baseURL = "https://rancher-sandbox.github.io/hypper.io/"
languageCode = "en-us"
theme = "portio-hugo"
title = "Hypper"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

[[menu.main]]


[params]
# rename when the logo is updated, so we indirectly also invalidate caches
logo = "images/hypper-logo-header.png"
githubLink = "https://github.com/rancher-sandbox/hypper"
docsLink = "https://github.com/rancher-sandbox/hypper/blob/main/docs/SUMMARY.md"
css = ["css/custom.css"]
favicon = "images/favicon.ico"
